{{- if .Values.hello.enabled -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.hello.name }}
  namespace: {{ .Values.hello.namespace }}
  labels:
    {{- toYaml .Values.hello.labels | nindent 4}}
spec:
  type: {{ .Values.hello.service.type }}
  ports:
    - port: {{ .Values.hello.service.port }}
      targetPort: {{ .Values.hello.containerPort }}
      name: http
  selector:
    {{- toYaml .Values.hello.labels | nindent 4}}
{{- end -}}
