# Default values for services.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

hello:
  enabled: true
  name: "hello"
  namespace: staging
  labels:
    app: hello
  replicaCount: 1

  image:
    repository: hanson.azurecr.io/9spokes
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "latest"

  containerPort: 8080

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi
  service:
    type: ClusterIP
    port: 80

  ingress:
    host: hansonli-svc.mooo.com

p2:
  enabled: true
  name: "p2"
  namespace: staging
  labels:
    app: p2

  image:
    repository: hanson.azurecr.io/9spokes
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "latest"

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi

p3:
  enabled: false
